name: binary_creation
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: generate loki.exe
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        spec: loki.spec
        path: .
    - name: generate loki-uprader.exe
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        spec: loki-upgrader.spec
        path: .
    - uses: actions/upload-artifact@v4
      with:
        name: loki.exe
        path: dist/windows
    - uses: actions/upload-artifact@v4
      with:
        name: loki-upgrader.exe
        path: dist/windows