name: binary_creation
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        spec: loki.spec
        path: .
    - uses: actions/upload-artifact@v4
      with:
        name: loki.exe
        path: dist/windows